### PR TITLE
feat: thschue stepping down from tc and maintainers

### PR DESCRIPTION
**Pull request by thschue**
I have been very inactive in the last few weeks/months due to many things I have on my agenda and am trying to refocus a bit. Therefore, I decided to step back as a TC member and maintainer (and get emeritus if possible). 

I want to thank the keptn community for the nice collaboration over the last few years. Maybe sometimes, I will be able to dedicate more time to this cool project!

### CODE REVIEW

**Review by AlexsJones — APPROVED** [review]

**Review by AnaMMedina21 — APPROVED** [review]
Thank you for all the contrubutions! +1 on emeritus for you

**Review by bradmccoydev — APPROVED** [review]

**Comment by bradmccoydev** [comment]
Thanks Thomas for all your hard work and getting the project to where it is today!

**Comment by agardnerIT** [comment]
Sad to see you go, but thanks for all your wonderful contributions. As Brad says, you were instrumental to this project. Good luck with everything the future holds!

**Review by thisthat — APPROVED** [review]
Thanks a lot @thschue, I had lot of fun working with you! Especially bootstrapping the Lifecycle Toolkit project. We are always welcoming you back at any time 😄

**Pull request merged**
