### PR TITLE
Add Keptn Emoji to branding directory and Slack 

### PR DESCRIPTION
**Pull request by subhamgcon**
Fixes Issue #122. Please review the emojis and feedback would be very helpful. Thank you and Have a nice day!

### CODE REVIEW

**Comment by subhamgcon** [comment]
Hey @oleg-nenashev, Thank you for the review! Yes, in the case of the images when I was using the remove background tool, the background Keptn logo was removed leaving the memes alone! That’s why the images have a non-transparent background.

**Comment by oleg-nenashev** [comment]
Added PNG in https://github.com/keptn/community/pull/128 . It is one that should render well. Or maybe not

on-fire

**Comment by subhamgcon** [comment]
@oleg-nenashev So is there any necessary edits?

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
@subhamgcon sorry for dropping the ball on it. AFAICT we discussed the following:

* Re-build GIFs with a proper PNG so that there are no glitches on the border
* Ensure all PNGs are submitted with transparent background

**Comment by subhamgcon** [comment]
@oleg-nenashev Edited and made all discussed changes! A review would be really helpful

**Review by oleg-nenashev — APPROVED** [review]
OK, fine with me. Not sure I would publish all of them, but makes sense to just merge

**Comment by oleg-nenashev** [comment]
Thanks for the update @subhamgcon ! I will submit my emojis in a follow-up

**Pull request merged**
