### PR TITLE
Clean up CODEOWNERS

### PR DESCRIPTION
**Pull request by thschue**
Signed-off-by: Thomas Schuetz <thomas.schuetz@dynatrace.com>

### CODE REVIEW

**Review by thisthat — APPROVED** [review]

**Comment by thisthat** [comment]
I would wait a period of 1week or all codeoweners approve  before we merge this PR so everyone could comment/reject this change.

**Review by grabnerandi — APPROVED** [review]
lgtm

**Review by mowies — COMMENTED** [review]
LGTM

**Comment by jetzlstorfer** [comment]
I was one of the CODEOWNERS but not removed. I'd appreciate some information upfront, although I understand that I was not very active in the past.

**Pull request merged**
